### ISSUE TITLE
$ is undefined error on https://auth.hasgeek.com/login

### ISSUE THREAD

**Issue by captn3m0** [hasgeek/lastuser#149]
This is the HTML content I get if I clear my cookies and open auth.hasgeek.com/login: https://gist.github.com/captn3m0/1d037f82e28440005413

jQuery is being loaded after the baseframe forms template, which tries to use jQuery, screwing up with things.

Google Chrome `47.0.2522.1 (Official Build) dev (64-bit)`

**Comment by karthikb351** [comment]
We are rendering the ajaxform JS code twice, the first time before baseframe is loaded and one again after. First one was always failing, but we didn't notice because the second one worked.

We should remove it from here - https://github.com/hasgeek/lastuser/blob/6bca3f4b0413b38f060bbfa2cbb4cc45c28ed625/lastuser_oauth/templates/forms/loginform.html#L13

and leave this one - https://github.com/hasgeek/lastuser/blob/6bca3f4b0413b38f060bbfa2cbb4cc45c28ed625/lastuser_oauth/templates/login.html#L50

**Comment by jace** [comment]
Removing it in `loginform.html` will break here: https://github.com/hasgeek/lastuser/blob/6bca3f4b0413b38f060bbfa2cbb4cc45c28ed625/lastuser_oauth/views/login.py#L67

We need to flag it instead so the line is skipped when `loginform.html` is included in `login.html`. The correct approach will be to (a) move the markup into a macro (minus the ajax setup), (b) call the macro from both `loginform.html` and `login.html`, and (c) avoid using an include to join templates, as includes lead to situations like this.
